# Generated by Django 5.2.16 on 2026-08-09 23:01

import apps.documents.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dental_cases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('STL', 'STL File'), ('XRAY', 'X-Ray'), ('PHOTO', 'Photograph'), ('PRESCRIPTION', 'Prescription'), ('SUPPORTING', 'Supporting Document')], max_length=20, verbose_name='File Category')),
                ('file', models.FileField(upload_to=apps.documents.models.case_file_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['stl', 'jpg', 'jpeg', 'png', 'pdf', 'doc', 'docx'])], verbose_name='File')),
                ('original_name', models.CharField(max_length=255, verbose_name='Original File Name')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Uploaded At')),
                ('dental_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='dental_cases.dentalcase', verbose_name='Dental Case')),
            ],
            options={
                'verbose_name': 'Case File',
                'verbose_name_plural': 'Case Files',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
