# Generated by Django 6.0.7 on 2026-08-08 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number', models.CharField(max_length=20)),
                ('current_stage', models.CharField(choices=[('RECEIVED', 'Received'), ('DESIGN', '3D Design'), ('PRINTING', 'Printing / Milling'), ('QC', 'Quality Control'), ('SHIPPED', 'Shipped')], default='RECEIVED', max_length=20)),
                ('comments', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Workflow',
                'verbose_name_plural': 'Workflows',
                'ordering': ['-updated_at'],
            },
        ),
    ]
