# Generated by Django 6.1.1 on 2026-09-08 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0002_case_tracking'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workflowupdate',
            options={'ordering': ['-created_at'], 'verbose_name': 'Workflow Update', 'verbose_name_plural': 'Workflow Updates'},
        ),
        migrations.AddField(
            model_name='workflowupdate',
            name='previous_stage',
            field=models.CharField(blank=True, choices=[('RECEIVED', 'Received'), ('DESIGN', '3D Design'), ('PRINTING', 'Printing / Milling'), ('QC', 'Quality Control'), ('SHIPPED', 'Shipped')], max_length=20, verbose_name='Previous stage'),
        ),
    ]
