# Generated by Django 6.1.1 on 2026-09-08 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratories', '0002_laboratory_case_users'),
        ('workflow', '0003_alter_workflowupdate_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Stage name')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('laboratory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_stages', to='laboratories.laboratory', verbose_name='Laboratory')),
            ],
            options={
                'verbose_name': 'Workflow Stage',
                'verbose_name_plural': 'Workflow Stages',
                'ordering': ['order', 'name'],
                'constraints': [models.UniqueConstraint(fields=('laboratory', 'name'), name='unique_stage_name_per_laboratory')],
            },
        ),
    ]
