# Generated by Django 5.2.16 on 2026-08-05 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Laboratory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone", models.CharField(max_length=20)),
                ("city", models.CharField(max_length=80)),
                ("address", models.CharField(max_length=200)),
                (
                    "service",
                    models.CharField(
                        choices=[
                            ("CROWN", "Dental Crowns"),
                            ("BRIDGE", "Dental Bridges"),
                            ("IMPLANT", "Dental Implants"),
                            ("ORTHODONTICS", "Orthodontics"),
                            ("PROSTHESIS", "Dental Prosthesis"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "rating",
                    models.DecimalField(decimal_places=1, default=0, max_digits=2),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
