# Generated by Django 6.0.7 on 2026-08-10 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DentalCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
('case_number', models.CharField(max_length=20, unique=True, verbose_name='Case Number')),
('clinic_name', models.CharField(max_length=150, verbose_name='Clinic')),
('requested_by', models.CharField(max_length=150, verbose_name='Requested By')),
('service_type', models.CharField(choices=[('CROWN', 'Dental Crown'), ('BRIDGE', 'Dental Bridge'), ('IMPLANT', 'Dental Implant'), ('VENEER', 'Dental Veneer'), ('ORTHODONTICS', 'Orthodontics'), ('OTHER', 'Other')], max_length=20, verbose_name='Service Type')),
('description', models.TextField(verbose_name='Description')),
('observations', models.TextField(blank=True, verbose_name='Observations')),
('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('IN_REVIEW', 'In Review'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='SUBMITTED', max_length=20, verbose_name='Status')),
('due_date', models.DateField(verbose_name='Due Date')),
('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),

            ],
            options={
                'verbose_name': 'Dental Case',
                'verbose_name_plural': 'Dental Cases',
                'ordering': ['-created_at'],
            },
        ),
    ]
