# Generated by Django 6.0.7 on 2026-09-07 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DentalCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number', models.CharField(max_length=20, unique=True)),
                ('clinic_name', models.CharField(max_length=150)),
                ('requested_by', models.CharField(max_length=150)),
                ('patient_reference', models.CharField(blank=True, max_length=100)),
                ('service_type', models.CharField(choices=[('CROWN', 'Dental Crown'), ('BRIDGE', 'Dental Bridge'), ('IMPLANT', 'Dental Implant'), ('VENEER', 'Dental Veneer'), ('ORTHODONTICS', 'Orthodontics'), ('OTHER', 'Other')], max_length=20)),
                ('description', models.TextField()),
                ('observations', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Dental Case',
                'verbose_name_plural': 'Dental Cases',
                'ordering': ['-created_at'],
            },
        ),
    ]
