# Generated by Django 6.0.7 on 2026-09-07 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dental_cases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DentalCaseFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='case_files/', verbose_name='File')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Uploaded At')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_files', to='dental_cases.dentalcase', verbose_name='Dental Case')),
            ],
            options={
                'verbose_name': 'Dental Case File',
                'verbose_name_plural': 'Dental Case Files',
            },
        ),
    ]
