# Generated by Django 6.1.1 on 2026-09-08 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dental_cases', '0002_dentalcasefile'),
        ('dental_cases', '0004_dentalcase_clinic'),
    ]

    operations = [
    ]
