# Generated by Django 5.2 on 2026-10-06 14:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0001_initial'),
        ('dental_cases', '0005_merge_0002_dentalcasefile_0004_dentalcase_clinic'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
                ('delivered_at', models.DateTimeField(auto_now_add=True, verbose_name='Delivered At')),
                ('notes', models.TextField(blank=True, verbose_name='Delivery Notes')),
                ('dental_case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_registration', to='dental_cases.dentalcase', verbose_name='Dental Case')),
                ('destination_clinic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='received_deliveries', to='clinics.clinic', verbose_name='Destination Clinic')),
                ('registered_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registered_deliveries', to=settings.AUTH_USER_MODEL, verbose_name='Registered By')),
            ],
            options={
                'verbose_name': 'Delivery Registration',
                'verbose_name_plural': 'Delivery Registrations',
                'ordering': ['-delivered_at'],
            },
        ),
    ]
